/**
 * LLM client module.
 *
 * This module is the single project entry point for LLM interaction. It handles:
 *   1. Sending user messages to OpenAI-compatible APIs such as OpenAI, Azure, and OpenRouter.
 *   2. Handling API responses: generated text, token usage, and success/retry/fatal status.
 *   3. Automatic retries for rate limits (429), server errors (5xx), network timeouts, and similar failures.
 *
 * Features moved to other modules:
 *   - Image preprocessing (processMessagesWithImages) -> utils.ts
 *   - Token estimation (estimateTokensFromText)       -> cost_calculator.ts
 *
 * Public functions:
 *   - callLlmApi() - low-level call that accepts a full message list and returns [status, result].
 *   - chat()       - simplified interface that wraps a single prompt string as a message list.
 */

// processMessagesWithImages: preprocess messages and convert local image paths to Base64 Data URLs.
// This used to live in llm_client.ts, but it belongs with image helpers such as
// imageToBase64 and getImageMimeType, so llm_client.ts can focus on HTTP calls.
import { processMessagesWithImages } from "./utils.js";

// estimateTokensFromText: estimate token counts from text length.
// This used to live in llm_client.ts, but token and cost logic is centralized in cost_calculator.ts.
import { estimateTokensFromText } from "./cost_calculator.js";
import {
  terminalInternalDebug,
  terminalInternalError,
  terminalInternalInfo,
  terminalInternalWarn,
} from "./core/terminal_reporter.js";

// ============================================================
// Simple logger
// ============================================================

/**
 * Simple logger that writes different log levels to the console.
 *
 * This module does not use the full logging system in src/core/logging.ts because
 * llm_client is a low-level module and should keep dependencies small to avoid cycles.
 *
 * The four levels map to console methods:
 *   - info:    general information, such as token estimates.
 *   - warning: warnings, such as an API response missing usage data.
 *   - error:   errors, such as failed image conversion.
 *   - debug:   debug details, such as successful image conversion.
 */
const logger = {
  info: (msg: string) => terminalInternalInfo(msg),
  warning: (msg: string) => terminalInternalWarn(msg),
  error: (msg: string) => terminalInternalError(msg),
  debug: (msg: string) => terminalInternalDebug(msg),
};

// ============================================================
// Type definitions
// ============================================================

/**
 * Message content block type.
 *
 * For multimodal messages, such as messages with both text and images, the
 * content field is an array and each item is a MessageContent value.
 *
 * Text block example:  { type: "text", text: "Describe this image" }
 * Image block example: { type: "image_url", image_url: { url: "data:image/png;base64,..." } }
 *
 * [key: string]: unknown allows arbitrary extra fields, similar to Python's
 * dict[str, Any]. This is useful because providers may define custom fields.
 */
export interface MessageContent {
  type: string;
  [key: string]: unknown;
}

/**
 * Single chat message type.
 *
 * role is the speaker role. Common values:
 *   - "system":    system instructions that shape AI behavior.
 *   - "user":      user input.
 *   - "assistant": AI response.
 *
 * content has two forms:
 *   - string: plain text message, the most common form.
 *     Example: { role: "user", content: "Hello" }
 *   - MessageContent[]: multimodal message with text, images, or other content blocks.
 *     Example: { role: "user", content: [
 *       { type: "text", text: "What is this?" },
 *       { type: "image_url", image_url: { url: "data:..." } }
 *     ]}
 */
export interface Message {
  role: string;
  content: string | MessageContent[];
}

/**
 * Token usage statistics type.
 *
 * Each API call returns, or estimates, token usage for cost calculation.
 *
 * prompt_tokens:      tokens consumed by input messages.
 * completion_tokens:  tokens consumed by the generated response.
 * total_tokens:       sum of prompt and completion tokens.
 * token_source:       source of the usage data.
 *   - "api":       provided directly by the API response, so it is accurate.
 *   - "estimated": estimated locally from text length, with some error but enough for cost tracking.
 */
export interface UsageDict {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  token_source: "api" | "estimated";
}

/**
 * Result returned by a successful LLM call.
 *
 * content: text generated by the AI.
 * usage:   token usage statistics for this call.
 */
export interface LlmResult {
  content: string;
  usage: UsageDict;
}

/**
 * LLM call status.
 *
 * "success":         call succeeded and result contains valid content.
 * "retriable_error": retryable error, such as a network timeout or rate limit.
 * "fatal_error":     fatal error, such as authentication failure or invalid parameters.
 */
export type LlmStatus = "success" | "retriable_error" | "fatal_error";

/**
 * Optional LLM call parameters.
 *
 * temperature:    generation randomness, from 0.0 most deterministic to 2.0 most random; default 0.7.
 * max_tokens:     maximum number of generated tokens; default 2000.
 * timeout:        per-request HTTP timeout in seconds; default 120.
 * max_retries:    maximum retry attempts; default 3.
 * retry_delay:    base retry delay in seconds; actual delay = retry_delay x attempt number.
 * extra_headers:  additional HTTP headers, such as the HTTP-Referer required by OpenRouter.
 *                 Record<string, string> is similar to Python's dict[str, str].
 * extra_params:   additional request-body parameters, such as a provider-specific thinking mode.
 *                 Record<string, unknown> is similar to Python's dict[str, Any].
 */
export interface LlmCallOptions {
  temperature?: number;
  max_tokens?: number;
  timeout?: number;
  max_retries?: number;
  retry_delay?: number;
  extra_headers?: Record<string, string>;
  extra_params?: Record<string, unknown>;
}

/**
 * Safety gate: whether LLM calls are enabled.
 *
 * Reads the LLM_API_ENABLE environment variable. Calls are allowed only when it
 * is explicitly set to one of these values, case-insensitively:
 *   "true" / "1" / "yes" / "on"
 * All other values return false by default, preventing accidental API costs.
 *
 * Equivalent to is_llm_enabled() in the Python safety.py module.
 */
function isLlmEnabled(): boolean {
  // Read the switch from the environment; unset means "false" and therefore disabled.
  const val = (process.env.LLM_API_ENABLE ?? "false").toLowerCase();
  // Only these values are considered enabled.
  return ["true", "1", "yes", "on"].includes(val);
}

// ============================================================
// Core API call
// ============================================================

/**
 * Unified low-level LLM API call.
 *
 * This is the unified entry point for all project LLM calls. It wraps the full
 * HTTP request/response flow:
 *   1. Preprocess messages, including image paths -> Base64.
 *   2. Build an OpenAI Chat Completions-compatible HTTP request.
 *   3. Send the request and handle the response.
 *   4. Classify errors and retry automatically.
 *
 * The return value is a [status, result] tuple:
 *   - when status is "success", result is LlmResult with content and usage.
 *   - when status is "retriable_error", result is { error: string } and callers may retry later.
 *   - when status is "fatal_error", result is { error: string } and retrying is not useful.
 *
 * Automatically retried error types:
 *   - HTTP 429 rate limits, 5xx server errors, and 408 request timeouts.
 *   - Network errors such as AbortError timeouts, SSL errors, and proxy errors.
 *   - Retry delay uses linear backoff: attempt N waits retry_delay x N seconds.
 *
 * @param messages Chat messages, which may contain image paths that are converted automatically.
 * @param apiUrl API endpoint URL, such as "https://api.openai.com/v1/chat/completions".
 * @param apiKey API key.
 * @param model Model name, such as "gpt-4o" or "claude-3-sonnet".
 * @param options Optional parameters such as temperature, max tokens, timeout, and retry settings.
 * @returns [status, result] tuple.
 */
export async function callLlmApi(
  messages: Message[],
  apiUrl: string,
  apiKey: string,
  model: string,
  options: LlmCallOptions = {}
): Promise<[LlmStatus, LlmResult | Record<string, unknown>]> {
  // Destructure parameters from options and assign defaults.
  //
  // Syntax note: const { key = defaultValue } = object
  //   - If object.key exists and is not undefined, use the provided value.
  //   - If object.key is missing or undefined, use the default on the right.
  //
  // Example: if the caller passes options = { temperature: 0.3 }
  //   temperature = 0.3    <- caller provided it.
  //   max_tokens  = 2000   <- caller did not provide it, so use the default.
  //   timeout     = 300    <- caller did not provide it, so use the default.
  //   ...and so on.
  const {
    temperature = 0.7,      // Generation randomness; 0 is most deterministic, 1 is more random.
    max_tokens = 50000,     // Maximum output tokens.
    timeout = 300,          // Request timeout in seconds; default 300 seconds, or 5 minutes.
    max_retries = 3,        // Maximum retry attempts after a failure.
    // retry_delay: seconds to wait between retries.
    // Prefer NETWORK_RETRY_DELAY so operations can tune it without changing code.
    // ?? "5" means use string "5" when the environment variable is unset.
    // parseFloat converts the environment string into a number.
    retry_delay = parseFloat(process.env["NETWORK_RETRY_DELAY"] ?? "5"),
    extra_headers,          // Optional extra HTTP headers; undefined when not provided.
    extra_params,           // Optional extra API parameters; undefined when not provided.
  } = options;

  // Step 1: preprocess messages, converting local image paths to Base64 Data URLs.
  const processedMessages = processMessagesWithImages(messages);

  // Step 2: request loop with retries.
  // attempt starts at 0 and can run at most max_retries times.
  for (let attempt = 0; attempt < max_retries; attempt++) {
    try {
      // Safety gate: if the check fails, return before making any network request.
      // Return "fatal" because retrying will not help until the setting changes.
      if (!isLlmEnabled()) {
        logger.warning("[SAFETY] LLM calls are disabled; skipping API request");
        return ["fatal_error", { error: "LLM calls are disabled (LLM_API_ENABLE is not enabled)" }];
      }

      // Step 3: build an OpenAI Chat Completions-compatible request body.
      // Reference: https://platform.openai.com/docs/api-reference/chat/create
      const payload: Record<string, unknown> = {
        model,                        // Model name.
        messages: processedMessages,  // Processed message list.
        temperature,                  // Generation randomness.
        max_tokens,                   // Maximum generated length.
      };

      // Merge extra parameters, such as provider-specific thinking switches or top_p.
      // Object.assign copies all extra_params properties onto payload.
      if (extra_params) {
        Object.assign(payload, extra_params);
      }

      // Build HTTP request headers.
      // Authorization: Bearer <key> is the standard authentication scheme for OpenAI-compatible APIs.
      const headers: Record<string, string> = {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      };

      // Merge extra headers, such as HTTP-Referer and X-Title required by OpenRouter.
      if (extra_headers) {
        Object.assign(headers, extra_headers);
      }

      // Step 4: send the HTTP request.
      // AbortController provides request timeout control and is built into Node.js 18+.
      const controller = new AbortController();
      // setTimeout calls abort() after timeout seconds. setTimeout uses milliseconds.
      const timeoutId = setTimeout(() => controller.abort(), timeout * 1000);

      let response: Response;
      try {
        // fetch is the built-in HTTP client in Node.js 18+.
        // signal connects fetch to AbortController, so abort() makes fetch throw AbortError.
        response = await fetch(apiUrl, {
          method: "POST",
          headers,
          body: JSON.stringify(payload),
          signal: controller.signal,
        });
      } finally {
        // Always clear the timer to avoid leaks, whether the request succeeds or fails.
        clearTimeout(timeoutId);
      }

      // ============================================================
      // Step 5: handle the HTTP response
      // ============================================================

      if (response.status === 200) {
        // ---- Successful response: parse JSON ----
        const responseData = await response.json() as Record<string, unknown>;

        // Extract generated text.
        // OpenAI response format: { choices: [{ message: { content: "..." }, finish_reason: "stop" }] }
        const choices = responseData["choices"] as Array<Record<string, unknown>> | undefined;
        // choices?.[0] is optional chaining; undefined choices will not throw.
        const choice = choices?.[0] ?? {};
        const message = choice["message"] as Record<string, unknown> | undefined;
        // Extract text content, defaulting to an empty string.
        let content = (message?.["content"] as string | undefined) ?? "";
        // Trim leading and trailing whitespace; APIs sometimes include newlines.
        if (content) content = content.trim();
        // finish_reason explains why generation stopped:
        //   "stop":   normal completion.
        //   "length": truncated by the max_tokens limit.
        const finishReason = choice["finish_reason"] as string | undefined;

        // Handle token usage; some providers may omit the usage field.
        // Standard OpenAI API responses include usage, but some third-party APIs do not.
        const usageRaw = responseData["usage"] as Record<string, number> | undefined;

        let usageDict: UsageDict;
        if (usageRaw) {
          // The API provided usage, so use it directly.
          usageDict = {
            prompt_tokens: usageRaw["prompt_tokens"] ?? 0,
            completion_tokens: usageRaw["completion_tokens"] ?? 0,
            total_tokens: usageRaw["total_tokens"] ?? 0,
            token_source: "api",
          };
        } else {
          // The API did not provide usage, so estimate it locally.
          // This is common with local deployments such as Ollama and some third-party proxies.
          logger.warning("API response is missing usage; estimating tokens for cost calculation");

          // Join all plain-text input messages to estimate prompt tokens.
          // Note: image content in multimodal messages cannot be estimated here.
          const promptText = processedMessages
            .map((msg) => (typeof msg.content === "string" ? msg.content : ""))
            .join(" ");
          const estimatedPrompt = estimateTokensFromText(promptText);
          // Estimate completion tokens from the generated text.
          const estimatedCompletion = estimateTokensFromText(content);

          usageDict = {
            prompt_tokens: estimatedPrompt,
            completion_tokens: estimatedCompletion,
            total_tokens: estimatedPrompt + estimatedCompletion,
            token_source: "estimated",
          };

          logger.info(
            `Token estimate: prompt≈${estimatedPrompt}, ` +
              `completion≈${estimatedCompletion}, ` +
              `total≈${usageDict.total_tokens}`
          );
        }

        // Build the final result.
        const resultDict: LlmResult = { content, usage: usageDict };

        // Determine call status from finish_reason.
        if (finishReason === "stop") {
          // Normal completion.
          return ["success", resultDict];
        } else if (finishReason === "length") {
          // Truncated by the max_tokens limit.
          logger.warning(
            `Response was truncated after ${usageDict.total_tokens} tokens ` +
              `(source: ${usageDict.token_source})`
          );
          // If there is content, treat it as success.
          if (content) return ["success", resultDict];
          // Truncated with no content means max_tokens needs to be increased.
          return [
            "fatal_error",
            { error: "Response was truncated and empty; increase max_tokens", usage: usageDict },
          ];
        } else {
          // Other finish reasons, such as "content_filter".
          if (content) {
            // Treat as success if content was returned, but keep a warning.
            logger.warning(`Unexpected finish reason: ${finishReason}, but content was received`);
            return ["success", resultDict];
          }
          return ["fatal_error", { error: `Unexpected finish reason: ${finishReason}` }];
        }
      }

      // ============================================================
      // HTTP error handling for non-200 status codes
      // ============================================================

      // Read the error response body as text for the error message.
      const responseText = await response.text();

      // Classify by HTTP status code.
      if (response.status === 400) {
        // 400 Bad Request: invalid parameters such as unsupported model or temperature.
        // Fatal until the caller fixes the request.
        return ["fatal_error", { error: `Client error (400): ${responseText}` }];
      } else if (response.status === 401 || response.status === 403) {
        // 401 Unauthorized / 403 Forbidden: invalid API key or missing permission.
        // Fatal until credentials are fixed.
        return ["fatal_error", { error: `Authentication error (${response.status}): ${responseText}` }];
      } else if (response.status === 404) {
        // 404 Not Found: API endpoint or model name does not exist.
        // Fatal until URL or model is fixed.
        return ["fatal_error", { error: `Resource not found (404): ${responseText}` }];
      } else if (response.status === 429) {
        // 429 Too Many Requests: rate limit exceeded.
        // Retry after a linearly increasing delay.
        if (attempt < max_retries - 1) {
          await sleep(retry_delay * (attempt + 1));
          continue;
        }
        // Retry attempts are exhausted; let the caller decide whether to retry later.
        return ["retriable_error", { error: `Rate limit (429): ${responseText}` }];
      } else if (response.status >= 500 && response.status < 600) {
        // 5xx server errors are usually temporary, so retry with linear delay.
        if (attempt < max_retries - 1) {
          await sleep(retry_delay * (attempt + 1));
          continue;
        }
        return ["retriable_error", { error: `Server error (${response.status}): ${responseText}` }];
      } else if (response.status === 408) {
        // 408 Request Timeout: server-side timeout, separate from client AbortError timeout.
        // Retry after a fixed delay.
        if (attempt < max_retries - 1) {
          await sleep(retry_delay);
          continue;
        }
        return ["retriable_error", { error: `Request timeout (408): ${responseText}` }];
      } else {
        // Other unexpected HTTP status codes, such as 418, are treated as fatal.
        return ["fatal_error", { error: `Unknown HTTP error (${response.status}): ${responseText}` }];
      }
    } catch (e) {
      // ============================================================
      // Network-level error handling
      // ============================================================

      if (e instanceof Error) {
        const name = e.name;
        const msg = e.message;

        if (name === "AbortError") {
          // AbortError: client-side timeout triggered by AbortController.
          // Retry because the server may be temporarily slow.
          if (attempt < max_retries - 1) {
            await sleep(retry_delay);
            continue;
          }
          return ["retriable_error", { error: "Request timed out" }];
        }

        if (msg.includes("SSL") || msg.includes("certificate")) {
          // SSL/TLS certificate errors: expired, self-signed, incomplete chain, and similar cases.
          // Retry because certificate validation can fail due to temporary network issues.
          logger.warning(`SSL certificate error (attempt ${attempt + 1}/${max_retries}): ${msg}`);
          if (attempt < max_retries - 1) {
            logger.info(`Waiting ${retry_delay} seconds before retry...`);
            await sleep(retry_delay);
            continue;
          }
          return [
            "retriable_error",
            {
              error: `SSL certificate validation failed after ${max_retries} attempts: ${msg}`,
              error_type: "ssl_error",
            },
          ];
        }

        if (msg.includes("proxy") || msg.includes("PROXY")) {
          // Proxy connection error: HTTP/HTTPS proxy is unreachable or refused the connection.
          // Retry because the proxy may be temporarily unavailable.
          logger.warning(`Proxy connection error: ${msg}`);
          if (attempt < max_retries - 1) {
            await sleep(retry_delay);
            continue;
          }
          return ["retriable_error", { error: `Proxy connection failed: ${msg}`, error_type: "proxy_error" }];
        }

        if (msg.includes("redirect") || msg.includes("REDIRECT")) {
          // Too many redirects usually means the API URL is misconfigured.
          // Fatal because retrying will not fix the URL.
          logger.error(`Too many redirects: ${msg}`);
          return [
            "fatal_error",
            { error: `Redirect limit exceeded: ${msg}`, error_type: "redirect_error" },
          ];
        }

        if (
          msg.includes("chunked") ||
          msg.includes("CHUNKED") ||
          msg.includes("incomplete") ||
          msg.includes("truncated")
        ) {
          // Chunked transfer error: HTTP chunked transfer encoding data was incomplete.
          // Equivalent to requests.exceptions.ChunkedEncodingError in Python.
          // Common causes include network instability or a server-side timeout.
          // Retry because this is usually temporary.
          logger.warning(`Chunked transfer error (attempt ${attempt + 1}/${max_retries}): ${msg}`);
          if (attempt < max_retries - 1) {
            await sleep(retry_delay);
            continue;
          }
          return [
            "retriable_error",
            { error: `Transfer interrupted: ${msg}`, error_type: "chunked_encoding_error" },
          ];
        }

        // Generic network errors: DNS failure, connection refused, unreachable network, and similar cases.
        // Retry because network problems are often temporary.
        if (attempt < max_retries - 1) {
          await sleep(retry_delay);
          continue;
        }
        return ["retriable_error", { error: `Request exception: ${msg}` }];
      }

      // e is not an Error instance, which is rare, such as throw "string" or throw 42.
      // Treat as fatal because the type cannot be classified.
      return ["fatal_error", { error: `Unknown error: ${e}` }];
    }
  }

  // All retries were exhausted. This should be unreachable, but keep it as a safety fallback.
  return ["retriable_error", { error: `Still failed after ${max_retries} attempts` }];
}

// ============================================================
// Simplified interface
// ============================================================

/**
 * Simplified chat interface.
 *
 * Useful for simple cases that send a single text message.
 * Internally wraps prompt as [{ role: "user", content: prompt }] before calling callLlmApi().
 *
 * Difference from callLlmApi:
 *   - callLlmApi returns a [status, result] tuple and leaves status handling to the caller.
 *   - chat returns LlmResult directly and throws on errors.
 *
 * Example:
 *   const result = await chat("Hello", apiUrl, apiKey, "gpt-4o");
 *   console.log(result.content);  // "Hello! How can I help?"
 *   console.log(result.usage);    // { prompt_tokens: 5, completion_tokens: 12, ... }
 *
 * @param prompt User input text.
 * @param apiUrl API endpoint URL.
 * @param apiKey API key.
 * @param model Model name.
 * @param options Optional parameters.
 * @returns LlmResult with generated text and token usage.
 * @throws Error for retriable or fatal errors.
 */
export async function chat(
  prompt: string,
  apiUrl: string,
  apiKey: string,
  model: string,
  options: LlmCallOptions = {}
): Promise<LlmResult> {
  // Wrap a single prompt as a standard message list.
  const messages: Message[] = [{ role: "user", content: prompt }];

  const [status, result] = await callLlmApi(messages, apiUrl, apiKey, model, options);

  if (status === "success") {
    // On success, result is LlmResult; the assertion tells TypeScript that.
    return result as LlmResult;
  } else if (status === "retriable_error") {
    // Retriable error: throw so the caller can catch it and decide whether to retry.
    // result may be { error: "..." }, so extract the message safely.
    const errorMsg =
      typeof result === "object" && result !== null && "error" in result
        ? result["error"]
        : String(result);
    throw new Error(`API call failed (retriable): ${errorMsg}`);
  } else {
    // Fatal error: also throw, but the caller should not retry unchanged.
    const errorMsg =
      typeof result === "object" && result !== null && "error" in result
        ? result["error"]
        : String(result);
    throw new Error(`API call failed (fatal): ${errorMsg}`);
  }
}

// ============================================================
// Utility functions
// ============================================================

/**
 * Wait asynchronously for the given number of seconds.
 *
 * Wraps setTimeout as a Promise so it can be used with async/await.
 * Used for retry delays.
 *
 * Example: await sleep(5)  // Wait 5 seconds.
 *
 * @param seconds Seconds to wait.
 * @returns Promise that resolves after the given number of seconds.
 */
function sleep(seconds: number): Promise<void> {
  // setTimeout uses milliseconds, so multiply seconds by 1000.
  // new Promise + resolve converts callback-style setTimeout into Promise style.
  return new Promise((resolve) => setTimeout(resolve, seconds * 1000));
}
