/**
 * PDF-to-image conversion utilities.
 *
 * This module renders PDF pages into JPEG files with mupdf.js. It supports
 * custom DPI, page-range selection, and resume behavior by skipping valid
 * image files that already exist in the output directory.
 */

import fs from "fs";
import path from "path";
import * as mupdf from "mupdf";

// ============================================================
// isImageValid
// ============================================================

/**
 * Check whether a generated image file exists and looks complete.
 *
 * This intentionally uses a lightweight validation rule. The images are
 * generated by this module, so checking for a reasonable file size is enough
 * to detect most interrupted or corrupted writes without adding another image
 * decoding dependency.
 */
export function isImageValid(imagePath: string): boolean {
  try {
    const stat = fs.statSync(imagePath);
    return stat.size >= 512;
  } catch {
    return false;
  }
}

// ============================================================
// parsePageRange
// ============================================================

/**
 * Parse a user-facing page range into 0-indexed page numbers.
 *
 * Supported formats:
 * - Single page: "5" -> [4]
 * - Range: "1-10" -> [0, 1, ..., 9]
 * - Mixed: "1-5,10,15-20"
 * - Empty or undefined: all pages
 */
export function parsePageRange(
  pageRange: string | undefined,
  totalPages: number
): number[] {
  if (!pageRange || pageRange.trim() === "") {
    return Array.from({ length: totalPages }, (_, i) => i);
  }

  const pages = new Set<number>();
  const parts = pageRange.replace(/ /g, "").split(",");

  for (const part of parts) {
    if (part.includes("-")) {
      const segments = part.split("-");
      if (segments.length !== 2) {
        throw new Error(`Invalid page range format: ${part}`);
      }

      const start = parseInt(segments[0]!, 10);
      const end = parseInt(segments[1]!, 10);

      if (isNaN(start) || isNaN(end)) {
        throw new Error(`Invalid page range format: ${part}`);
      }

      if (start < 1) {
        throw new Error(`Page range ${part} must start at page 1 or later`);
      }

      if (start > end) {
        throw new Error(
          `Invalid page range: ${part}, start page ${start} is greater than end page ${end}`
        );
      }

      if (start > totalPages) {
        throw new Error(
          `Page range ${part} starts beyond the PDF page count (1-${totalPages})`
        );
      }

      let adjustedEnd = end;
      if (end > totalPages) {
        console.log(
          `Page range ${part} ends beyond the PDF page count; adjusting: ${end} -> ${totalPages}`
        );
        adjustedEnd = totalPages;
      }

      for (let i = start - 1; i < adjustedEnd; i++) {
        pages.add(i);
      }
    } else {
      const page = parseInt(part, 10);

      if (isNaN(page)) {
        throw new Error(`Invalid page number: ${part}`);
      }

      if (page < 1 || page > totalPages) {
        throw new Error(`Page number ${page} is out of range (1-${totalPages})`);
      }

      pages.add(page - 1);
    }
  }

  return [...pages].sort((a, b) => a - b);
}

// ============================================================
// convertPdfToImages
// ============================================================

/**
 * Convert a PDF file into a sequence of JPEG images.
 *
 * The output files are named with 1-indexed page numbers:
 * `page_0001.jpg`, `page_0002.jpg`, and so on.
 */
export function convertPdfToImages(
  pdfPath: string,
  outputDir: string,
  dpi: number = 150,
  pageRange?: string
): string {
  if (!fs.existsSync(pdfPath)) {
    const errorMsg = `Error: PDF file not found at path: ${pdfPath}`;
    console.error(errorMsg);
    throw new Error(errorMsg);
  }

  fs.mkdirSync(outputDir, { recursive: true });
  console.log(`Images will be saved to: ${outputDir}`);
  console.log("Starting PDF to image conversion...");

  const pdfData = fs.readFileSync(pdfPath);
  const doc = mupdf.PDFDocument.openDocument(pdfData, "application/pdf");

  try {
    const totalPages = doc.countPages();
    const pagesToConvert = parsePageRange(pageRange, totalPages);

    if (pageRange) {
      console.log(`Converting ${pagesToConvert.length}/${totalPages} page(s)`);
    } else {
      console.log(`Converting all ${totalPages} page(s)`);
    }

    const existingImages = new Set<string>();
    if (fs.existsSync(outputDir)) {
      const files = fs.readdirSync(outputDir);
      for (const file of files) {
        if (file.startsWith("page_") && file.endsWith(".jpg")) {
          existingImages.add(file);
        }
      }
    }
    console.log(`Found ${existingImages.size} existing image file(s)`);

    const zoom = dpi / 72;
    let convertedCount = 0;

    for (const pageNum of pagesToConvert) {
      const imageName = `page_${String(pageNum + 1).padStart(4, "0")}.jpg`;
      const imagePath = path.join(outputDir, imageName);

      if (existingImages.has(imageName) && isImageValid(imagePath)) {
        console.log(`Skipping existing valid image: ${imageName}`);
        continue;
      } else if (existingImages.has(imageName) && !isImageValid(imagePath)) {
        console.log(`Found corrupted image file; regenerating: ${imageName}`);
      }

      const page = doc.loadPage(pageNum);
      const matrix = mupdf.Matrix.scale(zoom, zoom);
      const pixmap = page.toPixmap(matrix, mupdf.ColorSpace.DeviceRGB, false, true);

      const jpegData = pixmap.asJPEG(90);
      fs.writeFileSync(imagePath, jpegData);

      pixmap.destroy();
      page.destroy();

      convertedCount++;
    }

    console.log(
      `Conversion finished. Requested ${pagesToConvert.length} page(s); ` +
        `rendered ${convertedCount} new page(s) and skipped ${
          pagesToConvert.length - convertedCount
        } existing valid image(s).`
    );
    return outputDir;
  } finally {
    doc.destroy();
  }
}
